# Identifiants uniques du projet Backend
sonar.projectKey=kaba-delivery-backend
sonar.projectName=Kaba Delivery - Backend (Laravel)
sonar.projectVersion=1.0

# Chemins des sources à analyser
sonar.sources=app, config, database, routes
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Exclusions (fichiers générés ou tiers qui faussent les statistiques)
sonar.exclusions=vendor/**, storage/**, bootstrap/cache/**, database/migrations/**

#  Liens vers les rapports de tests pour le Quality Gate
sonar.php.coverage.reportPaths=tests/coverage/clover.xml
sonar.php.tests.reportPath=tests/coverage/junit.xml