sonar.organization=kakabi-christian
sonar.projectKey=kakabi-christian_KABA-DELIVERY
sonar.projectName=KABA-DELIVERY

# Sources de code utiles à analyser (on cible les dossiers contenant la logique métier)
sonar.sources=Backend/app, Backend/config, Frontend/src

# Spécification du dossier des tests pour le Backend
sonar.tests=Backend/tests

# Exclusions globales pour la sécurité et la performance
sonar.exclusions=**/vendor/**, **/node_modules/**, **/dist/**, **/storage/**, **/public/**, Frontend/vite.config.*